export interface ModuleData {
    slug: string;
    title: string;
    description: string;
    duration: string;
    chapters: number;
    missions: number;
    category: string;
    rating: number;
    enrolled: number;
    lastUpdated: string;
    videoUrl: string;
    overview: string;
    relatedModules: string[];
}

export const modulesData: ModuleData[] = [
    // Climate Action & Mitigation
    {
        slug: "climate-change-fundamentals",
        title: "Climate Change Fundamentals",
        description: "Understanding greenhouse gases and global warming impacts.",
        duration: "20 min",
        chapters: 4,
        missions: 3,
        category: "Climate",
        rating: 4.8,
        enrolled: 15420,
        lastUpdated: "Nov 10, 2025",
        videoUrl: "https://www.youtube.com/embed/dcBXMRZf-Qg",
        overview: "This comprehensive module explores the fundamental science behind climate change, including greenhouse gas emissions, global temperature rise, and their cascading effects on ecosystems and human societies.",
        relatedModules: ["Carbon Footprint Reduction", "Climate Adaptation Strategies", "Extreme Weather Patterns"],
    },
    {
        slug: "carbon-footprint-reduction",
        title: "Carbon Footprint Reduction",
        description: "Calculate and reduce your personal carbon emissions.",
        duration: "18 min",
        chapters: 3,
        missions: 2,
        category: "Climate",
        rating: 4.7,
        enrolled: 12350,
        lastUpdated: "Nov 8, 2025",
        videoUrl: "https://www.youtube.com/embed/8q7_aV8eLUE",
        overview: "Learn practical strategies to measure and minimize your carbon footprint through daily lifestyle choices, energy consumption patterns, and sustainable transportation options.",
        relatedModules: ["Climate Change Fundamentals", "Sustainable Transportation", "Energy Storage Solutions"],
    },
    {
        slug: "extreme-weather-patterns",
        title: "Extreme Weather Patterns",
        description: "How climate change affects floods, droughts, and storms.",
        duration: "15 min",
        chapters: 3,
        missions: 2,
        category: "Weather",
        rating: 4.6,
        enrolled: 11200,
        lastUpdated: "Nov 5, 2025",
        videoUrl: "https://www.youtube.com/embed/x-8n9zSxwl0",
        overview: "Explore the connection between climate change and extreme weather events including floods, droughts, hurricanes, and heat waves.",
        relatedModules: ["Climate Change Fundamentals", "Water Scarcity Solutions", "Climate Adaptation Strategies"],
    },
    {
        slug: "climate-adaptation-strategies",
        title: "Climate Adaptation Strategies",
        description: "Building resilient communities for climate challenges.",
        duration: "22 min",
        chapters: 4,
        missions: 3,
        category: "Climate",
        rating: 4.9,
        enrolled: 9800,
        lastUpdated: "Nov 12, 2025",
        videoUrl: "https://www.youtube.com/embed/dcBXMRZf-Qg",
        overview: "Discover innovative approaches to adapt to climate change impacts, from infrastructure design to community planning and disaster preparedness.",
        relatedModules: ["Climate Change Fundamentals", "Extreme Weather Patterns", "Green Urban Planning"],
    },
    // Renewable Energy
    {
        slug: "solar-energy-revolution",
        title: "Solar Energy Revolution",
        description: "Harness the power of the sun for clean electricity.",
        duration: "16 min",
        chapters: 3,
        missions: 2,
        category: "Energy",
        rating: 4.9,
        enrolled: 18500,
        lastUpdated: "Nov 12, 2025",
        videoUrl: "https://www.youtube.com/embed/Ep6yGFhTraE",
        overview: "Discover how solar photovoltaic technology converts sunlight into electricity and learn about the economics and environmental benefits of solar energy adoption.",
        relatedModules: ["Wind Power Technology", "Energy Storage Solutions", "Smart Grid Systems"],
    },
    {
        slug: "wind-power-technology",
        title: "Wind Power Technology",
        description: "How wind turbines generate sustainable energy.",
        duration: "14 min",
        chapters: 2,
        missions: 2,
        category: "Energy",
        rating: 4.7,
        enrolled: 14200,
        lastUpdated: "Nov 9, 2025",
        videoUrl: "https://www.youtube.com/embed/Ep6yGFhTraE",
        overview: "Learn about wind energy technology, from turbine design to wind farm operations, and understand its role in the renewable energy transition.",
        relatedModules: ["Solar Energy Revolution", "Hydroelectric Systems", "Energy Storage Solutions"],
    },
    {
        slug: "hydroelectric-systems",
        title: "Hydroelectric Systems",
        description: "Water-powered energy for sustainable communities.",
        duration: "12 min",
        chapters: 2,
        missions: 1,
        category: "Energy",
        rating: 4.5,
        enrolled: 10500,
        lastUpdated: "Nov 7, 2025",
        videoUrl: "https://www.youtube.com/embed/Ep6yGFhTraE",
        overview: "Understand how hydroelectric power plants generate clean electricity from flowing water and their environmental considerations.",
        relatedModules: ["Wind Power Technology", "Solar Energy Revolution", "Water Conservation Tech"],
    },
    {
        slug: "energy-storage-solutions",
        title: "Energy Storage Solutions",
        description: "Batteries and grid systems for renewable energy.",
        duration: "18 min",
        chapters: 3,
        missions: 2,
        category: "Energy",
        rating: 4.8,
        enrolled: 13700,
        lastUpdated: "Nov 11, 2025",
        videoUrl: "https://www.youtube.com/embed/Ep6yGFhTraE",
        overview: "Explore battery technologies, pumped hydro storage, and other solutions that enable reliable renewable energy systems.",
        relatedModules: ["Solar Energy Revolution", "Smart Grid Systems", "Green Technology Innovation"],
    },
    // Biodiversity Conservation
    {
        slug: "ecosystem-protection",
        title: "Ecosystem Protection",
        description: "Why biodiversity matters for planetary health.",
        duration: "17 min",
        chapters: 3,
        missions: 3,
        category: "Biodiversity",
        rating: 4.8,
        enrolled: 16300,
        lastUpdated: "Nov 10, 2025",
        videoUrl: "https://www.youtube.com/embed/GK_vRtHJZu4",
        overview: "Learn about the interconnected web of life and why protecting biodiversity is essential for ecosystem services and human survival.",
        relatedModules: ["Endangered Species Recovery", "Habitat Restoration Projects", "Ocean Conservation"],
    },
    {
        slug: "endangered-species-recovery",
        title: "Endangered Species Recovery",
        description: "Conservation efforts to save threatened wildlife.",
        duration: "15 min",
        chapters: 3,
        missions: 2,
        category: "Biodiversity",
        rating: 4.7,
        enrolled: 12800,
        lastUpdated: "Nov 8, 2025",
        videoUrl: "https://www.youtube.com/embed/GK_vRtHJZu4",
        overview: "Discover successful conservation programs and the science behind species recovery efforts worldwide.",
        relatedModules: ["Ecosystem Protection", "Habitat Restoration Projects", "Deforestation & Reforestation"],
    },
    {
        slug: "habitat-restoration-projects",
        title: "Habitat Restoration Projects",
        description: "Rebuilding natural environments for wildlife.",
        duration: "19 min",
        chapters: 4,
        missions: 3,
        category: "Biodiversity",
        rating: 4.9,
        enrolled: 11400,
        lastUpdated: "Nov 13, 2025",
        videoUrl: "https://www.youtube.com/embed/GK_vRtHJZu4",
        overview: "Engage with real-world habitat restoration projects and learn techniques for ecological recovery and rewilding.",
        relatedModules: ["Ecosystem Protection", "Deforestation & Reforestation", "Sustainable Agriculture"],
    },
    {
        slug: "ocean-conservation",
        title: "Ocean Conservation",
        description: "Protecting marine ecosystems and coral reefs.",
        duration: "16 min",
        chapters: 3,
        missions: 2,
        category: "Biodiversity",
        rating: 4.8,
        enrolled: 15900,
        lastUpdated: "Nov 9, 2025",
        videoUrl: "https://www.youtube.com/embed/GK_vRtHJZu4",
        overview: "Explore marine biodiversity threats including overfishing, pollution, and coral bleaching, plus conservation solutions.",
        relatedModules: ["Plastic Pollution Solutions", "Water Scarcity Solutions", "Ecosystem Protection"],
    },
    // Circular Economy & Waste Management
    {
        slug: "circular-economy-principles",
        title: "Circular Economy Principles",
        description: "Design out waste and keep resources in use.",
        duration: "20 min",
        chapters: 4,
        missions: 3,
        category: "Sustainability",
        rating: 4.9,
        enrolled: 17200,
        lastUpdated: "Nov 14, 2025",
        videoUrl: "https://www.youtube.com/embed/zCRKvDyyHmI",
        overview: "Understand the circular economy model that eliminates waste through better design, reuse, and regeneration of materials.",
        relatedModules: ["Waste Reduction Strategies", "Plastic Pollution Solutions", "Green Technology Innovation"],
    },
    {
        slug: "waste-reduction-strategies",
        title: "Waste Reduction Strategies",
        description: "Reduce, reuse, recycle for zero waste living.",
        duration: "14 min",
        chapters: 3,
        missions: 2,
        category: "Pollution",
        rating: 4.6,
        enrolled: 13500,
        lastUpdated: "Nov 6, 2025",
        videoUrl: "https://www.youtube.com/embed/zCRKvDyyHmI",
        overview: "Learn practical strategies for minimizing waste in daily life and moving toward zero-waste living.",
        relatedModules: ["Circular Economy Principles", "Composting & Organic Waste", "Plastic Pollution Solutions"],
    },
    {
        slug: "composting--organic-waste",
        title: "Composting & Organic Waste",
        description: "Turn food scraps into nutrient-rich soil.",
        duration: "12 min",
        chapters: 2,
        missions: 2,
        category: "Sustainability",
        rating: 4.7,
        enrolled: 11900,
        lastUpdated: "Nov 5, 2025",
        videoUrl: "https://www.youtube.com/embed/zCRKvDyyHmI",
        overview: "Master composting techniques to transform organic waste into valuable soil amendments for gardens and farms.",
        relatedModules: ["Waste Reduction Strategies", "Sustainable Agriculture", "Community Gardens & Food Security"],
    },
    {
        slug: "plastic-pollution-solutions",
        title: "Plastic Pollution Solutions",
        description: "Combat single-use plastics and ocean waste.",
        duration: "16 min",
        chapters: 3,
        missions: 3,
        category: "Pollution",
        rating: 4.8,
        enrolled: 19200,
        lastUpdated: "Nov 12, 2025",
        videoUrl: "https://www.youtube.com/embed/RS7IzU2VJIQ",
        overview: "Address the global plastic crisis through reduction strategies, alternatives, and innovative cleanup technologies.",
        relatedModules: ["Ocean Conservation", "Circular Economy Principles", "Waste Reduction Strategies"],
    },
    // Sustainable Communities
    {
        slug: "green-urban-planning",
        title: "Green Urban Planning",
        description: "Design cities for sustainability and livability.",
        duration: "21 min",
        chapters: 4,
        missions: 3,
        category: "Sustainability",
        rating: 4.9,
        enrolled: 14800,
        lastUpdated: "Nov 13, 2025",
        videoUrl: "https://www.youtube.com/embed/zCRKvDyyHmI",
        overview: "Explore sustainable urban design principles including green spaces, walkability, and climate-resilient infrastructure.",
        relatedModules: ["Sustainable Transportation", "Community Gardens & Food Security", "Smart Grid Systems"],
    },
    {
        slug: "sustainable-transportation",
        title: "Sustainable Transportation",
        description: "Electric vehicles, bikes, and public transit solutions.",
        duration: "15 min",
        chapters: 3,
        missions: 2,
        category: "Sustainability",
        rating: 4.7,
        enrolled: 16500,
        lastUpdated: "Nov 10, 2025",
        videoUrl: "https://www.youtube.com/embed/zCRKvDyyHmI",
        overview: "Learn about low-carbon transportation options from electric vehicles to bike infrastructure and mass transit systems.",
        relatedModules: ["Carbon Footprint Reduction", "Green Urban Planning", "Energy Storage Solutions"],
    },
    {
        slug: "community-gardens--food-security",
        title: "Community Gardens & Food Security",
        description: "Local food production for resilient communities.",
        duration: "17 min",
        chapters: 3,
        missions: 3,
        category: "Sustainability",
        rating: 4.8,
        enrolled: 12600,
        lastUpdated: "Nov 8, 2025",
        videoUrl: "https://www.youtube.com/embed/zCRKvDyyHmI",
        overview: "Discover how community gardens strengthen food security, build social connections, and promote sustainable agriculture.",
        relatedModules: ["Sustainable Agriculture", "Composting & Organic Waste", "Green Urban Planning"],
    },
    {
        slug: "environmental-justice",
        title: "Environmental Justice",
        description: "Equity and fairness in environmental protection.",
        duration: "19 min",
        chapters: 4,
        missions: 2,
        category: "Global Environmental",
        rating: 4.9,
        enrolled: 10800,
        lastUpdated: "Nov 14, 2025",
        videoUrl: "https://www.youtube.com/embed/zCRKvDyyHmI",
        overview: "Examine how environmental issues disproportionately affect marginalized communities and explore solutions for equity.",
        relatedModules: ["Climate Policy & Advocacy", "Sustainable Development Goals", "Green Urban Planning"],
    },
    // Green Innovation & Technology
    {
        slug: "green-technology-innovation",
        title: "Green Technology Innovation",
        description: "Cutting-edge solutions for environmental challenges.",
        duration: "18 min",
        chapters: 3,
        missions: 3,
        category: "Sustainability",
        rating: 4.9,
        enrolled: 15700,
        lastUpdated: "Nov 11, 2025",
        videoUrl: "https://www.youtube.com/embed/zCRKvDyyHmI",
        overview: "Explore emerging technologies addressing climate change, from carbon capture to sustainable materials and AI applications.",
        relatedModules: ["Smart Grid Systems", "Energy Storage Solutions", "Circular Economy Principles"],
    },
    {
        slug: "smart-grid-systems",
        title: "Smart Grid Systems",
        description: "Intelligent energy distribution for efficiency.",
        duration: "16 min",
        chapters: 3,
        missions: 2,
        category: "Energy",
        rating: 4.8,
        enrolled: 13200,
        lastUpdated: "Nov 9, 2025",
        videoUrl: "https://www.youtube.com/embed/Ep6yGFhTraE",
        overview: "Learn how smart grids optimize energy distribution, integrate renewables, and enable demand response programs.",
        relatedModules: ["Energy Storage Solutions", "Solar Energy Revolution", "Green Technology Innovation"],
    },
    {
        slug: "sustainable-agriculture",
        title: "Sustainable Agriculture",
        description: "Farming practices that protect the environment.",
        duration: "20 min",
        chapters: 4,
        missions: 3,
        category: "Sustainability",
        rating: 4.8,
        enrolled: 14300,
        lastUpdated: "Nov 12, 2025",
        videoUrl: "https://www.youtube.com/embed/zCRKvDyyHmI",
        overview: "Discover regenerative farming, organic methods, and precision agriculture that enhance soil health and biodiversity.",
        relatedModules: ["Community Gardens & Food Security", "Composting & Organic Waste", "Water Conservation Tech"],
    },
    {
        slug: "water-conservation-tech",
        title: "Water Conservation Tech",
        description: "Innovative solutions for water scarcity.",
        duration: "14 min",
        chapters: 3,
        missions: 2,
        category: "Global Environmental",
        rating: 4.7,
        enrolled: 12100,
        lastUpdated: "Nov 7, 2025",
        videoUrl: "https://www.youtube.com/embed/zCRKvDyyHmI",
        overview: "Explore water-saving technologies from drip irrigation to rainwater harvesting and desalination innovations.",
        relatedModules: ["Water Scarcity Solutions", "Sustainable Agriculture", "Hydroelectric Systems"],
    },
    // Air Quality & Pollution
    {
        slug: "air-quality-monitoring",
        title: "Air Quality Monitoring",
        description: "Understanding and measuring air pollution levels.",
        duration: "13 min",
        chapters: 2,
        missions: 2,
        category: "Pollution",
        rating: 4.6,
        enrolled: 10900,
        lastUpdated: "Nov 6, 2025",
        videoUrl: "https://www.youtube.com/embed/RS7IzU2VJIQ",
        overview: "Learn about air quality indices, monitoring technologies, and health impacts of various air pollutants.",
        relatedModules: ["Indoor Air Quality", "Industrial Emissions Control", "Climate Change Fundamentals"],
    },
    {
        slug: "indoor-air-quality",
        title: "Indoor Air Quality",
        description: "Creating healthy living and working environments.",
        duration: "11 min",
        chapters: 2,
        missions: 1,
        category: "Pollution",
        rating: 4.5,
        enrolled: 9500,
        lastUpdated: "Nov 4, 2025",
        videoUrl: "https://www.youtube.com/embed/RS7IzU2VJIQ",
        overview: "Understand indoor air pollutants and strategies for improving air quality in homes, schools, and workplaces.",
        relatedModules: ["Air Quality Monitoring", "Green Urban Planning", "Sustainable Living"],
    },
    {
        slug: "industrial-emissions-control",
        title: "Industrial Emissions Control",
        description: "Technologies to reduce factory pollution.",
        duration: "17 min",
        chapters: 3,
        missions: 2,
        category: "Pollution",
        rating: 4.7,
        enrolled: 11600,
        lastUpdated: "Nov 10, 2025",
        videoUrl: "https://www.youtube.com/embed/RS7IzU2VJIQ",
        overview: "Examine industrial pollution control technologies and regulations that reduce emissions from manufacturing.",
        relatedModules: ["Air Quality Monitoring", "Green Technology Innovation", "Climate Policy & Advocacy"],
    },
    // Global Environmental Issues
    {
        slug: "deforestation--reforestation",
        title: "Deforestation & Reforestation",
        description: "Protecting forests and planting for the future.",
        duration: "18 min",
        chapters: 3,
        missions: 3,
        category: "Global Environmental",
        rating: 4.8,
        enrolled: 16800,
        lastUpdated: "Nov 11, 2025",
        videoUrl: "https://www.youtube.com/embed/GK_vRtHJZu4",
        overview: "Understand deforestation drivers and participate in reforestation efforts to restore vital forest ecosystems.",
        relatedModules: ["Habitat Restoration Projects", "Carbon Footprint Reduction", "Biodiversity Conservation"],
    },
    {
        slug: "water-scarcity-solutions",
        title: "Water Scarcity Solutions",
        description: "Managing freshwater resources sustainably.",
        duration: "16 min",
        chapters: 3,
        missions: 2,
        category: "Global Environmental",
        rating: 4.7,
        enrolled: 13900,
        lastUpdated: "Nov 9, 2025",
        videoUrl: "https://www.youtube.com/embed/zCRKvDyyHmI",
        overview: "Address global water challenges through conservation, efficient use, and innovative water management strategies.",
        relatedModules: ["Water Conservation Tech", "Sustainable Agriculture", "Climate Adaptation Strategies"],
    },
    {
        slug: "sustainable-development-goals",
        title: "Sustainable Development Goals",
        description: "UN SDGs for a better world by 2030.",
        duration: "22 min",
        chapters: 4,
        missions: 3,
        category: "Global Environmental",
        rating: 4.9,
        enrolled: 18900,
        lastUpdated: "Nov 15, 2025",
        videoUrl: "https://www.youtube.com/embed/zCRKvDyyHmI",
        overview: "Explore the 17 UN Sustainable Development Goals and how they interconnect to create a sustainable future for all.",
        relatedModules: ["Environmental Justice", "Climate Policy & Advocacy", "Green Technology Innovation"],
    },
    {
        slug: "climate-policy--advocacy",
        title: "Climate Policy & Advocacy",
        description: "How governments and citizens drive change.",
        duration: "19 min",
        chapters: 4,
        missions: 2,
        category: "Global Environmental",
        rating: 4.8,
        enrolled: 12400,
        lastUpdated: "Nov 13, 2025",
        videoUrl: "https://www.youtube.com/embed/zCRKvDyyHmI",
        overview: "Learn about climate policy frameworks, international agreements, and how to advocate for environmental action.",
        relatedModules: ["Sustainable Development Goals", "Environmental Justice", "Climate Change Fundamentals"],
    },
];
